### ISSUE TITLE
if !conn.parent_connected || !conn.to_parent.is_empty()  line?

### ISSUE THREAD

**Issue by stransky** [the8472/weyland-p5000#1]
Hello, is this line correct?

``
            if !conn.parent_connected || !conn.to_parent.is_empty() {
                parent_flags |= PollFlags::OUT
            }
``

I'd expect we write to parent if it's connected, right? Should it be  conn.parent_connected && !conn.to_parent.is_empty()  ?

**Comment by the8472** [comment]
`!conn.to_parent.is_empty()` covers the case where we have data that was queued because we couldn't deliver it immediately. In that case we want POLLOUT to get notified when the socket is writable.

`!conn.parent_connected`  covers the non-blocking `connect()` call for the parent connection returning `EAGAIN`. To wait for connection completion we also want POLLOUT

**Comment by stransky** [comment]
I see, Thanks.
